### ISSUE TITLE
make all elements nillable?

### ISSUE THREAD

**Issue by georgschermann** [erasmus-without-paper/ewp-specs-api-factsheet#1]
It could be reasonable to make all elements nillable, at the moment it is not possible to generate a valid response with missing data.

**Comment by kamil-olszewski-uw** [comment]
We believe that we should not make mandatory fields optional. It is always possible, for example, to provide a link to the relevant information or simply the information "not applicable".

**Comment by wrygiel** [comment]
A lot of big techs have migrated towards the "always optional" approach. I
think it might be worth understanding why, to avoid stumbling on similar
problems they did in the past. For example, some quick read here:
https://stackoverflow.com/a/31814967

**Comment by janinamincer-daszkiewicz** [comment]
The discussion is about Protocol Buffers, not factsheets ;) This makes a difference. I bet that there will be HEIs wanting to show the National Agency that they have imlemented Factsheet API but implemented it by sending all nulls.
In Erasmus World we *do* need information from the partners so by making the fields required we strongly encourage them to deliver useful content. Delivering useless content would be a real shame.
There are not so many fields and all of them are for useful information.
We already suffer in many places because of lack of data which has been left optional to make the implementation easier.
Do not changing from required to optional also allow us not to change what has already been specified and implemented by many.
